server:
  port: 8080

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://118.31.21.206:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always